POST http://localhost:6969/api/auth/register
Content-Type: application/json

{
    "username":"1",
    "password":"1"
}

###
POST http://localhost:6969/api/auth/login
Content-Type: application/json

{
    "username":"minhhoangdeptrai",
    "password":"1"
}

###
GET http://localhost:5000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjRlNWUwNzlhZmI0NWQ2OWMyMzRmYjciLCJpYXQiOjE2NDkzMDMyOTl9.7NdEbUhkvzDBjLcc5duPgnGHSwsiZTHYa57h6_HOTlM

# {
#     "title":"PT",
#     "description": "Shopping",
#     "url":"facebook.com/hadat921",
#     "status":"GYM KÈM PT", 
# }

###
GET http://localhost:6969/api/post/getAll
Authorization: Beare eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQ4MDgyZGI1YjYwZDJhNWJmZGEwNzgiLCJyb2xlaWQiOiIxIiwiaWF0IjoxNjQ5ODU0MzU0fQ.g8-2CU9pfA0FUo4lytUn8qzRRXnF560FhKAMrLXBy1c

###
PUT http://localhost:6969/api/post/update:62546065c5c0764bed8328ba
Content-Type: application/json
Authorization: Beare eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQ4MDgyZGI1YjYwZDJhNWJmZGEwNzgiLCJyb2xlaWQiOiIxIiwiaWF0IjoxNjQ5NzQxMjQ5fQ.SfWrLX2UX4p3LsBIG3aB7FTYQvGGCO2BsZo43D0RcmE

{
    "title":"Vue",
    "description":"Hihi",
    "status":"LEARNING"
}

#######################

POST http://localhost:6969/api/post/add
Content-Type: application/json
Authorization: Beare eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjU0NDNmMTZmOGE2MGM2Y2MyMDA4ZmEiLCJyb2xlaWQiOiIwIiwiaWF0IjoxNjQ5NjkzNTk3fQ.__fEJJOGnCJEQXQZo-5FkDCeMH5xHoK6ZKrtogJueqU

{
    "title":"PT",
    "description": "Shopping",
    "url":"facebook.com/hadat921",
    "status":"GYM KÈM PT"
}

###
DELETE http://localhost:5000/api/post/62546065c5c0764bed8328ba
Authorization: Beare eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQ1ZTE0MzZmNzBjYTQ5NWU2NTJlNjIiLCJpYXQiOjE2NDg3ODE0NjZ9.g3WRLP1ZIF115mY0KZ_irclBS6hvWQTi5oX1S2uETMo

############################
GET http://localhost:6969/api/course/62550fdcc516e99fd4d99482
Content-Type: application/json
Authorization: Beare eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQ4MDgyZGI1YjYwZDJhNWJmZGEwNzgiLCJyb2xlaWQiOiIxIiwiaWF0IjoxNjQ5ODU0MzU0fQ.g8-2CU9pfA0FUo4lytUn8qzRRXnF560FhKAMrLXBy1c

############################
POST http://localhost:6969/api/course/add/62550fdcc516e99fd4d99482
Content-Type: application/json
Authorization: Beare eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQ4MDgyZGI1YjYwZDJhNWJmZGEwNzgiLCJyb2xlaWQiOiIxIiwiaWF0IjoxNjQ5Nzc1MjQ3fQ.O2U_uR1e41LS-5ZjHN8jAmg-dTTEhMXXyLRgx_YH_38

{
    "title":"pascal",
    "description": "Ông trùm mongodb"
}

#################################
PUT http://localhost:6969/api/course/update/625593031cba5e986ebb2157
Content-Type: application/json
Authorization: Beare eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQ4MDgyZGI1YjYwZDJhNWJmZGEwNzgiLCJyb2xlaWQiOiIxIiwiaWF0IjoxNjQ5Nzc1MjQ3fQ.O2U_uR1e41LS-5ZjHN8jAmg-dTTEhMXXyLRgx_YH_38

{
    "title":"C#",
    "description": "Ông trùm mongodb HUTECH"
}

#######################
DELETE http://localhost:6969/api/course/delete/625593031cba5e986ebb2157
Content-Type: application/json
Authorization: Beare eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQ4MDgyZGI1YjYwZDJhNWJmZGEwNzgiLCJyb2xlaWQiOiIxIiwiaWF0IjoxNjQ5Nzc1MjQ3fQ.O2U_uR1e41LS-5ZjHN8jAmg-dTTEhMXXyLRgx_YH_38
